import '../../../core/network/api_client.dart';
import '../../../core/network/api_response.dart';

/// 日记列表项（对应 api.md diary list item）
class DiaryListItem {
  final String diaryId;
  final String date;
  final String title;
  final String avatar;
  final int emotion;

  const DiaryListItem({
    required this.diaryId,
    required this.date,
    required this.title,
    required this.avatar,
    required this.emotion,
  });

  factory DiaryListItem.fromJson(Map<String, dynamic> json) {
    final content = json['content'] as String? ?? '';
    return DiaryListItem(
      diaryId: (json['diaryId'] ?? json['id'] ?? '').toString(),
      date: json['date'] as String? ?? '',
      title: json['title'] as String? ??
          (content.isNotEmpty
              ? content.substring(0, content.length > 20 ? 20 : content.length)
              : ''),
      avatar: json['avatar'] as String? ?? json['imagePath'] as String? ?? '',
      emotion: json['emotion'] as int? ?? 0,
    );
  }
}

/// 日记列表响应
class DiaryListResponse {
  final List<DiaryListItem> diaryList;

  const DiaryListResponse({required this.diaryList});

  factory DiaryListResponse.fromJson(Map<String, dynamic> json) {
    final list = (json['diaryList'] as List<dynamic>?) ??
        (json['diaries'] as List<dynamic>?) ??
        const [];
    return DiaryListResponse(
      diaryList: list
          .map((e) => DiaryListItem.fromJson(e as Map<String, dynamic>))
          .toList(),
    );
  }
}

/// 日记详情响应
class DiaryDetailResponse {
  final String date;
  final String title;
  final String avatar;
  final int emotion;
  final String content;
  final List<String> imageList;

  const DiaryDetailResponse({
    required this.date,
    required this.title,
    required this.avatar,
    required this.emotion,
    required this.content,
    required this.imageList,
  });

  factory DiaryDetailResponse.fromJson(Map<String, dynamic> json) {
    final images = json['imageList'] as List<dynamic>? ?? [];
    return DiaryDetailResponse(
      date: json['date'] as String? ?? '',
      title: json['title'] as String? ?? '',
      avatar: json['avatar'] as String? ?? '',
      emotion: json['emotion'] as int? ?? 0,
      content: json['content'] as String? ?? '',
      imageList: images.map((e) => e.toString()).toList(),
    );
  }
}

/// 自动生成日记响应
class AutoGenerateDiaryResponse {
  final bool generated;
  final String diaryId;
  final int contentLength;
  final String date;

  const AutoGenerateDiaryResponse({
    required this.generated,
    required this.diaryId,
    required this.contentLength,
    required this.date,
  });

  factory AutoGenerateDiaryResponse.fromJson(Map<String, dynamic> json) {
    return AutoGenerateDiaryResponse(
      generated: json['generated'] as bool? ?? false,
      diaryId: (json['diaryId'] ?? '').toString(),
      contentLength: json['contentLength'] as int? ?? 0,
      date: (json['date'] ?? '').toString(),
    );
  }
}

/// 日记相关 API 调用
class DiaryApiService {
  final ApiClient _client;

  DiaryApiService({ApiClient? client}) : _client = client ?? ApiClient();

  /// 获取日记列表
  Future<ApiResponse<DiaryListResponse>> getDiaryList(String petId) {
    return _client.get<DiaryListResponse>(
      '/api/mengyu/diaries',
      queryParams: {'petId': petId},
      fromJson: (json) =>
          DiaryListResponse.fromJson(json as Map<String, dynamic>),
    );
  }

  /// 获取日记详情
  ///
  /// 优先使用 [diaryId] 查询，为空时使用 [date] 查询
  Future<ApiResponse<DiaryDetailResponse>> getDiaryDetail({
    required String petId,
    String? diaryId,
    String? date,
  }) {
    if (diaryId != null && diaryId.isNotEmpty) {
      return _client.get<DiaryDetailResponse>(
        '/api/mengyu/diaries/$diaryId',
        fromJson: (json) =>
            DiaryDetailResponse.fromJson(json as Map<String, dynamic>),
      );
    }

    final params = <String, String>{'petId': petId};
    if (date != null) params['date'] = date;
    return _client.get<DiaryDetailResponse>(
      '/api/mengyu/pet/detail',
      queryParams: params,
      fromJson: (json) =>
          DiaryDetailResponse.fromJson(json as Map<String, dynamic>),
    );
  }

  /// 自动生成某一天的日记（基于服务端已上传照片）
  Future<ApiResponse<AutoGenerateDiaryResponse>> autoGenerateDiary({
    required String petId,
    required String date,
  }) {
    return _client.post<AutoGenerateDiaryResponse>(
      '/api/mengyu/ai/diary/auto-generate',
      body: {
        'petId': petId,
        'date': date,
      },
      fromJson: (json) =>
          AutoGenerateDiaryResponse.fromJson(json as Map<String, dynamic>),
    );
  }
}
