import 'package:flutter/foundation.dart';
import 'package:pet_diary/data/models/diary_entry.dart';
import 'package:pet_diary/data/models/pet.dart';
import 'package:pet_diary/data/models/quota_status.dart';
import 'package:pet_diary/data/data_sources/remote/diary_api_service.dart';
import 'package:pet_diary/data/repositories/diary_repository.dart';
import 'package:pet_diary/data/repositories/pet_repository.dart';
import 'package:pet_diary/domain/services/quota_service.dart';

class DiaryViewModel extends ChangeNotifier {
  final DiaryRepository _diaryRepository = DiaryRepository();
  final PetRepository _petRepository = PetRepository();
  final DiaryApiService _diaryApiService = DiaryApiService();
  final QuotaService _quotaService = QuotaService();

  List<DiaryEntry> _entries = [];
  int _currentIndex = 0;
  bool _isLoading = false;
  String? _errorMessage;
  Pet? _currentPet;
  QuotaStatus _quotaStatus = const QuotaStatus();

  // Getters
  List<DiaryEntry> get entries => _entries;
  int get currentIndex => _currentIndex;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;
  Pet? get currentPet => _currentPet;
  QuotaStatus get quotaStatus => _quotaStatus;

  /// 当前显示的日记
  DiaryEntry? get currentEntry {
    if (_entries.isEmpty || _currentIndex >= _entries.length) {
      return null;
    }
    return _entries[_currentIndex];
  }

  /// 是否有上一页
  bool get hasPrevious => _currentIndex > 0;

  /// 是否有下一页
  bool get hasNext => _currentIndex < _entries.length - 1;

  /// 初始化
  Future<void> init() async {
    await loadData();
    await refreshQuotaStatus();
    await _autoGenerateRecentDiariesIfNeeded();
  }

  /// 刷新配额状态
  Future<void> refreshQuotaStatus() async {
    try {
      _quotaStatus = await _quotaService.getQuotaStatus();
      _applyEntryAccessRules();
      debugPrint(
        '📊 [Diary] AI配额(剩余/总): ${_quotaStatus.freeQuotaRemaining}/${_quotaStatus.freeQuotaTotal}, '
        '已用: ${_quotaStatus.freeQuotaUsed}, 会员: ${_quotaStatus.isPremium}',
      );
      notifyListeners();
    } catch (e) {
      debugPrint('❌ [Diary] 刷新配额状态失败: $e');
    }
  }

  /// 加载所有数据 — 优先从服务端，fallback 到本地
  Future<void> loadData() async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      // 加载宠物信息
      _currentPet = await _petRepository.getCurrentPet();

      if (_currentPet != null) {
        // 尝试从服务端加载日记
        final loaded = await _loadFromServer(_currentPet!.id);
        if (!loaded) {
          // Fallback 到本地
          debugPrint('[Diary] Server unavailable, loading from local');
          _entries = await _diaryRepository.getRecentEntries(limit: 30);
        }
      } else {
        _entries = await _diaryRepository.getRecentEntries(limit: 30);
      }

      _applyEntryAccessRules();
      debugPrint('✅ 数据加载完成');
      debugPrint('📚 [Diary] 当前展示日记数量(服务端/本地): ${_entries.length}');
    } catch (e) {
      _errorMessage = '加载数据失败：$e';
      debugPrint('❌ 加载错误: $e');
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> _autoGenerateRecentDiariesIfNeeded() async {
    if (_currentPet == null) return;

    if (!_quotaStatus.canGenerateAI) {
      debugPrint('ℹ️ [Diary] 自动生成跳过：配额不足');
      return;
    }

    final now = DateTime.now();
    final baseDay = DateTime(now.year, now.month, now.day);
    final targetDays = <DateTime>[
      baseDay,
      baseDay.subtract(const Duration(days: 1)),
      baseDay.subtract(const Duration(days: 2)),
    ];

    var remaining = _quotaStatus.freeQuotaRemaining;
    var generatedAny = false;

    try {
      for (final day in targetDays) {
        if (!_quotaStatus.isPremium && remaining <= 0) {
          break;
        }

        final dayStr =
            '${day.year}-${day.month.toString().padLeft(2, '0')}-${day.day.toString().padLeft(2, '0')}';

        DiaryEntry? existingEntry;
        for (final entry in _entries) {
          final d = DateTime(entry.date.year, entry.date.month, entry.date.day);
          if (d == day) {
            existingEntry = entry;
            break;
          }
        }

        if (existingEntry != null && existingEntry.content.trim().isNotEmpty) {
          continue;
        }

        debugPrint('🤖 [Diary] 自动尝试生成日记: $dayStr');
        final response = await _diaryApiService.autoGenerateDiary(
          petId: _currentPet!.id,
          date: dayStr,
        );

        if (!response.success || response.data == null) {
          debugPrint('⚠️ [Diary] $dayStr 自动生成失败: ${response.errorMessage}');
          continue;
        }

        if (!response.data!.generated) {
          debugPrint('ℹ️ [Diary] $dayStr 无可生成内容（缺照片或已有内容）');
          continue;
        }

        generatedAny = true;
        debugPrint(
          '✅ [Diary] 自动生成成功: date=$dayStr, diaryId=${response.data!.diaryId}',
        );

        await _quotaService.recordAIUsage();
        if (!_quotaStatus.isPremium) {
          remaining--;
        }
      }

      if (generatedAny) {
        await refreshQuotaStatus();
        await loadData();
      }
    } catch (e) {
      debugPrint('❌ [Diary] 自动生成日记异常: $e');
    }
  }

  void _applyEntryAccessRules() {
    if (_entries.isEmpty) return;

    if (_quotaStatus.isPremium) {
      _entries = _entries.map((e) => e.copyWith(isLocked: false)).toList();
      return;
    }

    // 免费用户仅可查看前 3 篇日记（按当前列表顺序）
    _entries = _entries.asMap().entries.map((item) {
      final index = item.key;
      final entry = item.value;
      final canView = index < 3;
      return entry.copyWith(isLocked: !canView);
    }).toList();
  }

  /// 从服务端加载日记列表 + 详情（含 imageList）
  Future<bool> _loadFromServer(String petId) async {
    try {
      // 1. 获取日记列表
      final listResponse = await _diaryApiService.getDiaryList(petId);
      if (!listResponse.success || listResponse.data == null) {
        debugPrint('[Diary] Failed to load diary list from server');
        return false;
      }

      final diaryList = listResponse.data!.diaryList;
      if (diaryList.isEmpty) {
        _entries = [];
        return true;
      }

      // 2. 获取每条日记的详情（含 imageList）
      final entries = <DiaryEntry>[];
      for (final item in diaryList) {
        final detailResponse = await _diaryApiService.getDiaryDetail(
          petId: petId,
          diaryId: item.diaryId,
        );

        if (detailResponse.success && detailResponse.data != null) {
          final detail = detailResponse.data!;
          entries.add(DiaryEntry(
            id: item.diaryId,
            petId: petId,
            date: DateTime.tryParse(detail.date) ?? DateTime.now(),
            content: detail.content,
            imagePath: detail.avatar.isNotEmpty ? detail.avatar : null,
            imageUrls: detail.imageList,
            isLocked: false,
            createdAt: DateTime.tryParse(detail.date) ?? DateTime.now(),
          ));
        }
      }

      _entries = entries;
      debugPrint('[Diary] Loaded ${entries.length} entries from server');
      return true;
    } catch (e) {
      debugPrint('[Diary] Server load error: $e');
      return false;
    }
  }

  /// 翻到上一页
  void previousPage() {
    if (hasPrevious) {
      _currentIndex--;
      notifyListeners();
    }
  }

  /// 翻到下一页
  void nextPage() {
    if (hasNext) {
      _currentIndex++;
      notifyListeners();
    }
  }

  /// 跳转到指定索引
  void jumpToIndex(int index) {
    if (index >= 0 && index < _entries.length) {
      _currentIndex = index;
      notifyListeners();
    }
  }

  /// 删除日记
  Future<void> deleteEntry(String id) async {
    try {
      await _diaryRepository.deleteEntry(id);
      _entries = _entries.where((e) => e.id != id).toList();
      if (_currentIndex >= _entries.length && _currentIndex > 0) {
        _currentIndex = _entries.length - 1;
      }
      notifyListeners();
      debugPrint('✅ 日记已删除');
    } catch (e) {
      _errorMessage = '删除失败：$e';
      notifyListeners();
      debugPrint('❌ 删除日记错误: $e');
    }
  }
}
